name: cua_hang_thoi_trang
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # App Architecture & State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  meta: ^1.12.0

  # Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.20.0
  # firebase_storage: is removed

  # image_picker: is removed

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
