// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3-Aoa5XlE5MaiCncaQevCFGEd1csuN_Q',
    appId: '1:525585549713:web:b9fa0f17b71a5eca2af230',
    messagingSenderId: '525585549713',
    projectId: 'duonwwggg',
    authDomain: 'duonwwggg.firebaseapp.com',
    storageBucket: 'duonwwggg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP3E8nwrCf_HtxZfevZsaXczdkoci4tRw',
    appId: '1:525585549713:android:92f18e4a928971ec2af230',
    messagingSenderId: '525585549713',
    projectId: 'duonwwggg',
    storageBucket: 'duonwwggg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFrmZVz3kzXFh8vCiGkY4cev3UtP4c610',
    appId: '1:525585549713:ios:2156c8997f7a1d1f2af230',
    messagingSenderId: '525585549713',
    projectId: 'duonwwggg',
    storageBucket: 'duonwwggg.firebasestorage.app',
    iosBundleId: 'com.example.cuaHangThoiTrang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFrmZVz3kzXFh8vCiGkY4cev3UtP4c610',
    appId: '1:525585549713:ios:2156c8997f7a1d1f2af230',
    messagingSenderId: '525585549713',
    projectId: 'duonwwggg',
    storageBucket: 'duonwwggg.firebasestorage.app',
    iosBundleId: 'com.example.cuaHangThoiTrang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3-Aoa5XlE5MaiCncaQevCFGEd1csuN_Q',
    appId: '1:525585549713:web:499f7e5a185d98b02af230',
    messagingSenderId: '525585549713',
    projectId: 'duonwwggg',
    authDomain: 'duonwwggg.firebaseapp.com',
    storageBucket: 'duonwwggg.firebasestorage.app',
  );
}
